//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaasEcom.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SaasEcom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaasEcom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaasEcom.Core.Resources.SaasEcom", typeof(SaasEcom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string BillingAddress_AddressLine1_Address_1 {
            get {
                return ResourceManager.GetString("BillingAddress_AddressLine1_Address_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string BillingAddress_AddressLine2_Address_2 {
            get {
                return ResourceManager.GetString("BillingAddress_AddressLine2_Address_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string BillingAddress_City_City {
            get {
                return ResourceManager.GetString("BillingAddress_City_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string BillingAddress_Country_Country {
            get {
                return ResourceManager.GetString("BillingAddress_Country_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BillingAddress_Name_Name {
            get {
                return ResourceManager.GetString("BillingAddress_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string BillingAddress_State_State {
            get {
                return ResourceManager.GetString("BillingAddress_State_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        public static string BillingAddress_Vat_VAT_Number {
            get {
                return ResourceManager.GetString("BillingAddress_Vat_VAT_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string BillingAddress_ZipCode_Zip_Code {
            get {
                return ResourceManager.GetString("BillingAddress_ZipCode_Zip_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CreditCard_AddressCity_City {
            get {
                return ResourceManager.GetString("CreditCard_AddressCity_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your City..
        /// </summary>
        public static string CreditCard_AddressCity_Please_enter_your_City_ {
            get {
                return ResourceManager.GetString("CreditCard_AddressCity_Please_enter_your_City_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CreditCard_AddressCountry_Country {
            get {
                return ResourceManager.GetString("CreditCard_AddressCountry_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Country.
        /// </summary>
        public static string CreditCard_AddressCountry_Please_enter_your_Country {
            get {
                return ResourceManager.GetString("CreditCard_AddressCountry_Please_enter_your_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CreditCard_AddressLine1_Address {
            get {
                return ResourceManager.GetString("CreditCard_AddressLine1_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your address..
        /// </summary>
        public static string CreditCard_AddressLine1_Please_enter_your_address_ {
            get {
                return ResourceManager.GetString("CreditCard_AddressLine1_Please_enter_your_address_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string CreditCard_AddressLine2_Address {
            get {
                return ResourceManager.GetString("CreditCard_AddressLine2_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CreditCard_AddressState_State {
            get {
                return ResourceManager.GetString("CreditCard_AddressState_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Post Code..
        /// </summary>
        public static string CreditCard_AddressZip_Please_enter_your_Post_Code_ {
            get {
                return ResourceManager.GetString("CreditCard_AddressZip_Please_enter_your_Post_Code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string CreditCard_AddressZip_Post_code {
            get {
                return ResourceManager.GetString("CreditCard_AddressZip_Post_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CreditCard_CardNumber_Card_Number {
            get {
                return ResourceManager.GetString("CreditCard_CardNumber_Card_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 digits only.
        /// </summary>
        public static string CreditCard_Cvc__3_digits_only {
            get {
                return ResourceManager.GetString("CreditCard_Cvc__3_digits_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC.
        /// </summary>
        public static string CreditCard_Cvc_CVC {
            get {
                return ResourceManager.GetString("CreditCard_Cvc_CVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string CreditCard_Cvc_Required {
            get {
                return ResourceManager.GetString("CreditCard_Cvc_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string CreditCard_ExpirationMonth_Invalid {
            get {
                return ResourceManager.GetString("CreditCard_ExpirationMonth_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreditCard_Name_Name {
            get {
                return ResourceManager.GetString("CreditCard_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name on the card..
        /// </summary>
        public static string CreditCard_Name_Please_enter_the_name_on_the_card_ {
            get {
                return ResourceManager.GetString("CreditCard_Name_Please_enter_the_name_on_the_card_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 months.
        /// </summary>
        public static string SubscriptionInterval_EverySixMonths_Every_6_months {
            get {
                return ResourceManager.GetString("SubscriptionInterval_EverySixMonths_Every_6_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3 months.
        /// </summary>
        public static string SubscriptionInterval_EveryThreeMonths_Every_3_months {
            get {
                return ResourceManager.GetString("SubscriptionInterval_EveryThreeMonths_Every_3_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string SubscriptionInterval_Monthly_Monthly {
            get {
                return ResourceManager.GetString("SubscriptionInterval_Monthly_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string SubscriptionInterval_Weekly_Weekly {
            get {
                return ResourceManager.GetString("SubscriptionInterval_Weekly_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        public static string SubscriptionInterval_Yearly_Yearly {
            get {
                return ResourceManager.GetString("SubscriptionInterval_Yearly_Yearly", resourceCulture);
            }
        }
    }
}
