// <auto-generated />
namespace SaasEcom.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SubscriptionPlanValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubscriptionPlanValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201405102049234_SubscriptionPlanValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
